### ISSUE TITLE
Fatal error prevents the main program from opening

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#11]
![截图未命名0103125028](https://user-images.githubusercontent.com/61811583/147900477-6289b327-af50-4830-8cb2-5364c90669e9.png)

**Comment by 110-kenichi** [comment]
Sorry for late reply.
I've fixed the critical issue.

https://github.com/110-kenichi/mame/releases/tag/v4.1.0.2

**Comment by denjhang** [comment]
ok
