### ISSUE TITLE
Support OPL3 hardware pass-through

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#13]
Add a feature that allows MAmidiMEmo to directly use a sound card with OPL3, usually on port 220 or 388.

**Comment by 110-kenichi** [comment]
You can play OPL3 musics with a real OPL3 sound card of CMI by installing the my custom sound driver.

See the manual.

![image](https://user-images.githubusercontent.com/40394569/174352382-6d2de119-a152-472e-aa90-0dd7b9afff22.png)
