### ISSUE TITLE
YM2612 VGM recording is abnormal.

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#18]
[YM2612_0_2022-4-14_23-24-49_0.zip](https://github.com/110-kenichi/mame/files/8490413/YM2612_0_2022-4-14_23-24-49_0.zip)
It looks like channel 456 doesn't seem to have the FM timbre parameter written, resulting in no sound for channel 456.
![截图未命名0414232945](https://user-images.githubusercontent.com/61811583/163423277-55ee33c1-02ca-4e4a-8b61-831f179c1679.jpeg)

**Comment by 110-kenichi** [comment]
Thank you for reporting!

I've fixed. Please grab updated version from here.
https://github.com/110-kenichi/mame/releases/tag/v4.1.0.7

Now, the MAmi re-init the FM registers for writing a VGM file, so you don't need to init FM registers by your hand.
