### ISSUE TITLE
Importing timbres/instruments from external files?

### ISSUE THREAD

**Issue by AugiteSoul** [110-kenichi/mame#2]
Hello, is there a way to load instruments from either instrument files such as .opm (YM2151, YM2612 patches) or .brr (SPC700 sample data), or directly from ripped video game music data (e.g: .spc for Super Famicom music, .vgm for a large number of chips, some of which are covered by your software, .nsf for Famicom, .mdx for X68000, etc...)?
If not, do you think it could be a worthy addition? Either way, MAmidiMEmo is a rather useful tool, so thanks for developing it.

**Comment by 110-kenichi** [comment]
1) Can I get ".opm" file specification from where? Do you know?
2) You can load a brr file from the [AdpcmData]
![image](https://user-images.githubusercontent.com/40394569/160725168-a1381336-276d-4361-82ba-295824ec9a06.png)
3) It is so hard to import nsf,mdx file...
