### ISSUE TITLE
Gigatron sound engine support

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#24]
Gigatron is an 8bit computer composed of only 7400 series chips, and it has a 4-channel PSG. At present, I have developed a music engine using C language for Gigatron. If you are interested, I hope you can add Gigatron to the MAmi Project.
Actually I want to be able to convert midi to array of gigatron music engine using MAmi Project.

**Comment by 110-kenichi** [comment]
Currently, MAME does not support it. So cant.
