### ISSUE TITLE
OPL3 CNT value?

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#25]
![截图未命名0618082642](https://user-images.githubusercontent.com/61811583/174432229-95a608dc-d4c3-41db-95e6-49d1170a1151.jpeg)
I don't understand this popup. What is CNT value? And the pop-up doesn't seem to be able to close since it appeared.

**Comment by 110-kenichi** [comment]
@denjhang could you please tell me the procedure to reproduce this issue?

**Comment by 110-kenichi** [comment]
Fixed on v4.1.1.1
https://github.com/110-kenichi/mame/releases/tag/v4.1.1.1

@denjhang
