### ISSUE TITLE
Play midi files in playlist in order

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#26]
Thanks for the ability to add playlists. But in order to go with the automatic VGM recording function, I think you also need to add the ability to automatically switch tracks, so that after playing a midi file, Mami will automatically play the next file.
It would be convenient if this could be achieved. I will use Mami to batch convert midi to VGM.

**Comment by 110-kenichi** [comment]
Implemented the feature. Could you please check this ? @denjhang 

https://github.com/110-kenichi/mame/releases/tag/v4.1.2.0

**Comment by denjhang** [comment]
Thank you, I'm recording the Goldberg Variations in version YM2151.
