### ISSUE TITLE
Adapt to RetroWave OPL3 and Arduino OPL2/OPL3DUO(hardware playback VGM).

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#30]
https://shop.sudomaker.com/products/retrowave-opl3-express
RetroWave OPL3 is a hardware with MCU and OPL3 chip, it can be connected to computer via usb.
A program is shown here to play VGM using RetroWave OPL3.https://github.com/SudoMaker/RetroWave/tree/master/Player
RetroWave OPL3 is connected to the computer in the form of a serial device through USB, such as COM5.
Currently DOSBOX-X is compatible with this hardware.

https://github.com/DhrBaksteen/ArduinoOPL2
Arduino OPL2 allows to use serial port to control YM3812 or YMF262, I hope vgmplay can adapt to this function.
I made a USB-OPL3 based on Arduino OPL2, and currently I can use Dosbox-X+sbvgm to play music from OPL1/2/3.
https://github.com/DhrBaksteen/ArduinoOPL2/blob/master/examples/OPL3Duo/SerialPassthrough/SerialPassthrough.ino
https://github.com/DhrBaksteen/ArduinoOPL2/blob/master/examples/OPL2AudioBoard/SerialPassthrough/SerialPassthrough.ino

Currently I use SerialPassthrough.ino of OPL3DUO, compile these codes with arduino and upload them to arduino nano.
After that I use dosbox-x and specify the port number (like com3) and I can use the actual opl3 hardware.

In addition to using dosbox-x to access opl3duo, you can also use opl3bankeditor
https://github.com/Wohlstand/OPL3BankEditor

and an immature vgm player made by my friend.
https://github.com/zhblue/OPL3USB/tree/main/vgmplay2usb

**Comment by 110-kenichi** [comment]
・Basically, Homebrew hardware is not supported.
・I do not have the hardware.
・I need the cooperation of its developers.
