### ISSUE TITLE
OPLL preset melody/drum Timbres larger than 128 cannot be auditioned.

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#37]
I discovered that the drum sounds were mapped to timbres. But for the preset drums of the OPL series, if I do not set ADSR and TL, only use the default parameters, and set "DrumSetEnhanced", I find that I will not be able to audition such drum sounds, because when I click the FM register, the ToneType will Automatically changes to Custom (0), this should be a bug.

**Comment by 110-kenichi** [comment]
FM registers can be editable for Custom sound only.
Please close FM register editor for DrumSet.
