### ISSUE TITLE
ADSR control of PSG/WSG

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#6]
I know that PSG/WSG can only use software to control the volume envelope. However, the ADSR volume control of PSG/WSG is implemented in MML2VGM, which will make the sound more natural (compared to a pure volume change array)

**Comment by 110-kenichi** [comment]
You mean the the MAmidiMEmo ADSR is not natural?

![image](https://user-images.githubusercontent.com/40394569/160724895-0b65aed3-0ad3-4065-94b0-f16b1145fdd8.png)

**Comment by denjhang** [comment]
I mean, add an ADSR envelope adjustment similar to FM for PSG. I know that PSG does not support hardware ADSR envelopes, but a software envelope suitable for PSG can be calculated by ADSR.Like in mml2vgm.
![截图未命名0330125305](https://user-images.githubusercontent.com/61811583/160754097-71ee66fe-3ab8-4ac5-85e4-a66d4aa9a432.jpeg)

**Comment by 110-kenichi** [comment]
Hmm...? Already exists ADSR( AR,DR,SL,RR ) for PSG and so on.

**Comment by denjhang** [comment]
Well, then I hope the PSG series can have a graphical adjustment window like FM.

**Comment by 110-kenichi** [comment]
Ah, I see...

**Comment by denjhang** [comment]
I tested PSG's so-called ADSR and I found that it decayed too quickly, stopping almost immediately after the note ended. I wish PSG could also slowly decay volume after release like FM. like this.Wouldn't it be better if PSG also had these 6 FM parameters.
![截图未命名0330184940](https://user-images.githubusercontent.com/61811583/160814949-c2e701d6-d243-470b-a6a1-1526114048ec.jpeg)

**Comment by 110-kenichi** [comment]
You mean that RR is too fast even if you set RR value to 127?
