### ISSUE TITLE
Automatic naming of recording files

### ISSUE THREAD

**Issue by denjhang** [110-kenichi/mame#9]
I hope that when playing a MIDI file and turning on WAV or VGM recording, the MIDI file name can be automatically used as the WAV or VGM file name.

**Comment by 110-kenichi** [comment]
Added "Auto Rec VGM","Auto Rec WAV" button to MIDI player.
Output VGM files to the <MIDI file name> folder.
Output a WAV file to the <MIDI file name>.wav

**Comment by denjhang** [comment]
Thanks for implementing this feature.
